AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
  App:
    Type: String
  UsersTableName:
    Type: String
  OrdersTableName:
    Type: String

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${App}-${Env}-${UsersTableName}"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST 

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${App}-${Env}-${OrdersTableName}"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: orderId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  UsersTableArn:
    Value: !GetAtt UsersTable.Arn
  OrdersTableArn:
    Value: !GetAtt OrdersTable.Arn
  # OrdersTableName: 
  #   Value: !GetAtt OrdersTable.TableName.OrdersTableName
