AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
  App:
    Type: String
  ReportsBucketName:
    Type: String

Resources:
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${App}-${Env}-${ReportsBucketName}"