AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  OrdersTable:
    Type: String

    
Resources:
  createOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.createOrderHandler
      CodeUri: ../../src/api/orders/
      Timeout: 28
      Runtime: nodejs18.x
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: post
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - handler.ts

  getOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/api/orders/
      Handler: handler.getOrderHandler
      Timeout: 28
      Runtime: nodejs18.x
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: get
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - handler.ts
  
  updateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/api/orders/
      Handler: handler.updateOrderHandler
      Timeout: 28
      Runtime: nodejs18.x
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: put
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - handler.ts

  deleteOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/api/orders/
      Handler: handler.deleteOrderHandler
      Timeout: 28
      Runtime: nodejs18.x
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: delete
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - handler.ts