AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Stack

Resources:
  DyanmoDBCrudPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
            Resource: '*'
  
  DynamoDBCrudRole:
    